[svn-r17089] Description: 	Bring r16548:17085 from trunk to file_free_space branch.
Tested on:
        FreeBSD/32 6.3 (duty) in debug mode
        FreeBSD/64 6.3 (liberty) w/C++ & FORTRAN, in debug mode
        Linux/32 2.6 (jam) w/PGI compilers, w/C++ & FORTRAN, w/threadsafe,
                                in debug mode
        Linux/64-amd64 2.6 (smirom) w/Intel compilers w/default API=1.6.x,
                                w/C++ & FORTRAN, in production mode
        Solaris/32 2.10 (linew) w/deprecated symbols disabled, w/C++ & FORTRAN,
                                w/szip filter, in production mode
        Linux/64-ia64 2.6 (cobalt) w/Intel compilers, w/C++ & FORTRAN,
                                in production mode
        Linux/64-ia64 2.4 (tg-login3) w/parallel, w/FORTRAN, in production mode
        Linux/64-amd64 2.6 (abe) w/parallel, w/FORTRAN, in production mode
        Mac OS X/32 10.5.7 (amazon) in debug mode
        Mac OS X/32 10.5.7 (amazon) w/C++ & FORTRAN, w/threadsafe,
                                in production mode

diff --git a/tools/h5repack/h5repack.sh.in b/tools/h5repack/h5repack.sh.in
--- a/tools/h5repack/h5repack.sh.in
+++ b/tools/h5repack/h5repack.sh.in
@@ -53,6 +53,8 @@ FILE12=h5repack_nbit.h5
 FILE13=h5repack_soffset.h5
 FILE14=h5repack_layouto.h5      # A file with an older version of the layout message
                                 # (copy of test/tlayouto.h5)
+FILE15=h5repack_named_dtypes.h5
+FILE16=tfamily%05d.h5           # located in common testfiles folder
 
 
 nerrors=0
@@ -139,6 +141,8 @@ TOOLTEST()
     rm -f $outfile
 }
 
+# same as TOOLTEST, but it uses the old syntax -i input_file -o output_file
+#
 TOOLTEST0() 
 {
     # Run test.
@@ -154,6 +158,38 @@ TOOLTEST0()
      $RUNSERIAL $H5REPACK_BIN -i $infile -o $outfile $@
     else
      $RUNSERIAL $H5REPACK_BIN -i $infile -o $outfile "$@"
+    fi
+
+    RET=$?
+    if [ $RET != 0 ] ; then
+     echo "*FAILED*"
+     nerrors="`expr $nerrors + 1`"
+    else
+     echo " PASSED"
+     DIFFTEST $infile $outfile
+    fi
+    rm -f $outfile
+}
+
+
+# same as TOOLTEST, but it uses the common testfiles at $srcdir/../testfiles/
+# used to test the family driver, where these files reside
+#
+TOOLTEST1() 
+{
+    # Run test.
+    # Tflops interprets "$@" as "" when no parameter is given (e.g., the
+    # case of missing file name).  Changed it to use $@ till Tflops fixes it.
+    TESTING $H5REPACK $@
+
+    infile=$srcdir/../testfiles/$1
+    path=`pwd`
+    outfile=$path/out.$1
+    shift
+    if [ "`uname -s`" = "TFLOPS O/S" ]; then
+     $RUNSERIAL $H5REPACK_BIN $@ $infile $outfile
+    else
+     $RUNSERIAL $H5REPACK_BIN "$@" $infile $outfile
     fi
 
     RET=$?
@@ -455,7 +491,10 @@ TOOLTEST $FILE4 -l dset_chunk:CONTI
 TOOLTEST $FILE4 -l dset_chunk:CHUNK=18x13
 
 # Native option
-TOOLTEST $FILE1 -n
+# Do not use FILE1, as the named dtype will be converted to native, and h5diff will
+# report a difference.
+TOOLTEST $FILE0 -n
+TOOLTEST $FILE2 -n
 
 
 # latest file format with long switches. use FILE4=h5repack_layout.h5 (no filters)
@@ -503,6 +542,15 @@ TOOLTEST $arg
 # Check repacking file with old version of layout message (should get upgraded
 #       to new version and be readable, etc.)
 TOOLTEST $FILE14
+
+# test for datum size > H5TOOLS_MALLOCSIZE
+TOOLTEST $FILE1 -f GZIP=1
+
+# Check repacking file with committed datatypes in odd configurations
+TOOLTEST $FILE15
+
+# tests family driver (file is located in common testfiles folder, uses TOOLTEST1
+TOOLTEST1 $FILE16
 
 if test $nerrors -eq 0 ; then
    echo "All $H5REPACK tests passed."
