[svn-r5806] Purpose:     Update, Feature add, Fix Description:     - Added support for GPFS. It checks for GPFS automagically (by seeing       if the gpfs.h file is present and the gpfs_fcntl() function is       available). The macro which enables this is H5_HAVE_GPFS. This is       only implemented in the h5perf (pio) performance tests, though...
    - Fixed the Linux large file check. It failed for RedHat 7.3 machines
      because the getdents64() wasn't available.

    - Revamped the ENABLE/WITH help messages to use the autoconf
      AC_HELP_STRING macro which formats things just nicely,
      thankyouverymuch.

    - Revamped how checks for compression were being done. It's now one
      macro (H5_HAVE_COMPRESSION) which you have to check for instead of
      three (H5_HAVE_{ZLIB,LIBZ_H,COMPRESS2}).
Solution:
    - Changed Linux LFS check to test whether the kernel version was
      >2.4 or not. The override still works, though, so if you have a
      <2.4 system but are sure that the FS can handle >2GB files, then
      you can use the --enable-linux-lfs flag for that.
Platforms tested:
    AIX and Linux (2.2 and 2.4)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -991,27 +991,27 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --disable-hsizet        Datasets can normally be larger than memory
-                          and/or files but some compilers are unable to
-                          handle this (including versions of GCC before
-                          2.8.0). Disabling the feature causes dataset
-                          sizes to be restricted to the size of core memory,
-                          or 'size_t'.
-  --enable-fortran        Compile the Fortran interface default=no
-  --enable-cxx            Compile the C++ interface default=no
-  --enable-static-exec    Build only statically linked executables default=no
+  --disable-hsizet        Datasets can normally be larger than memory and/or
+                          files but some compilers are unable to handle this
+                          (including versions of GCC before 2.8.0). Disabling
+                          the feature causes dataset sizes to be restricted to
+                          the size of core memory, or 'size_t'.
+  --enable-fortran        Compile the Fortran interface [default=no]
+  --enable-cxx            Compile the C++ interface [default=no]
+  --enable-static-exec    Build only statically linked executables
+                          [default=no]
   --enable-shared=PKGS  build shared libraries default=yes
   --enable-static=PKGS  build static libraries default=yes
   --enable-fast-install=PKGS  optimize for fast installation default=yes
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-production     Determines how to run the compiler.
   --enable-linux-lfs      Enable support for large (64-bit) files on Linux.
-                          default=check
+                          [default=check]
   --enable-threadsafe     Enable thread safe capability
   --enable-hdf5v1_2       Compile the HDF5 v1.2 compatibility interface
-                          default=no
-  --enable-stream-vfd     Build the Stream Virtual File Driver default=no
-  --enable-debug=all    Turn on debugging in all packages. One may also
+                          [default=no]
+  --enable-stream-vfd     Build the Stream Virtual File Driver [default=no]
+  --enable-debug=all      Turn on debugging in all packages. One may also
                           specify a comma-separated list of package names
                           without the leading H5 or the word no. The default
                           is most packages.
@@ -1032,12 +1032,12 @@ Optional Packages:
     --with-xxx=DIR     - Specify only the directory which contains the
                          include/ and lib/ subdirectories
 
-  --with-dmalloc=DIR    Use dmalloc memory debugging aid (default=no)
-  --with-zlib=DIR       Use GNU zlib compression default=yes
-  --with-ssl=LIB        Use the SSL library default=no
-  --with-gass=DIR       Use the GASS library default=no
-  --with-srb=DIR        Use the SRB Library default=no
-  --with-pthread=DIR    Use the Pthreads library default=no
+  --with-dmalloc=DIR      Use dmalloc memory debugging aid [default=no]
+  --with-zlib=DIR         Use GNU zlib compression [default=yes]
+  --with-ssl=LIB          Use the SSL library [default=no]
+  --with-gass=DIR         Use the GASS library [default=no]
+  --with-srb=DIR          Use the SRB Library [default=no]
+  --with-pthread=DIR      Use the Pthreads library [default=no]
 
 Some influential environment variables:
   CC          C compiler command
@@ -2392,7 +2392,7 @@ if test "${enable_fortran+set}" = set; then
   HDF_FORTRAN=$enableval
 fi;
 
-if test "X$HDF_FORTRAN" = "Xyes"; then
+if test "x$HDF_FORTRAN" = "xyes"; then
   echo "yes"
   if test -z "$config_dirs"; then
     config_dirs="fortran"
@@ -2411,7 +2411,7 @@ if test "${enable_cxx+set}" = set; then
   HDF_CXX=$enableval
 fi;
 
-if test "X$HDF_CXX" = "Xyes"; then
+if test "x$HDF_CXX" = "xyes"; then
   echo "yes"
   if test -z "$config_dirs"; then
     config_dirs="c++"
@@ -2435,7 +2435,7 @@ if test "${enable_static_exec+set}" = set; then
   STATIC_EXEC=$enableval
 fi;
 
-if test "X$STATIC_EXEC" = "Xyes"; then
+if test "x$STATIC_EXEC" = "xyes"; then
   echo "yes"
   LT_STATIC_EXEC="-all-static"
 else
@@ -2445,7 +2445,7 @@ fi
 
 
  PERL=""
-if test "X$GCC" = "Xyes"; then
+if test "x$GCC" = "xyes"; then
   for ac_prog in perl
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -8488,87 +8488,17 @@ fi;
       X-no)
         ;;
       X-|*)
+        MAJOR_VER="`uname -r | cut -d '.' -f1`"
+        MINOR_VER="`uname -r | cut -d '.' -f2`"
 
-for ac_func in getdents64
-do
-as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $ac_func" >&5
-echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
-if eval "test \"\${$as_ac_var+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-/* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char $ac_func (); below.  */
-#include <assert.h>
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char $ac_func ();
-char (*f) ();
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-/* The GNU C library defines this for functions which it implements
-    to always fail with ENOSYS.  Some functions are actually named
-    something starting with __ and the normal name is an alias.  */
-#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
-choke me
-#else
-f = $ac_func;
-#endif
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  eval "$as_ac_var=yes"
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-eval "$as_ac_var=no"
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
-if test `eval echo '${'$as_ac_var'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
-_ACEOF
-                                                                                             LINUX_LFS=yes
-fi
-done
-
+        if test $MAJOR_VER -ge 2 -a $MINOR_VER -ge 4; then
+          LINUX_LFS="yes"
+        fi
         ;;
     esac
 
-    echo "$as_me:$LINENO: checking for large file support on linux mode" >&5
-echo $ECHO_N "checking for large file support on linux mode... $ECHO_C" >&6
+    echo "$as_me:$LINENO: checking for large file support mode on Linux" >&5
+echo $ECHO_N "checking for large file support mode on Linux... $ECHO_C" >&6
     if test "X$LINUX_LFS" = "Xyes"; then
       echo "$as_me:$LINENO: result: enabled" >&5
 echo "${ECHO_T}enabled" >&6
@@ -22789,7 +22719,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
-
+ HAVE_ZLIB_H="yes"
 fi
 
 done
@@ -22859,6 +22789,74 @@ _ACEOF
 
 else
   unset HAVE_ZLIB
+fi
+
+    echo "$as_me:$LINENO: checking for compress2" >&5
+echo $ECHO_N "checking for compress2... $ECHO_C" >&6
+if test "${ac_cv_func_compress2+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char compress2 (); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char compress2 ();
+char (*f) ();
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_compress2) || defined (__stub___compress2)
+choke me
+#else
+f = compress2;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_compress2=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_func_compress2=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_compress2" >&5
+echo "${ECHO_T}$ac_cv_func_compress2" >&6
+if test $ac_cv_func_compress2 = yes; then
+  HAVE_COMPRESS2="yes"
 fi
 
     ;;
@@ -23000,7 +22998,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
-
+ HAVE_ZLIB_H="yes"
 else
   CPPFLAGS="$saved_CPPFLAGS"
 fi
@@ -23076,11 +23074,87 @@ _ACEOF
   LIBS="-lz $LIBS"
 
 else
-  LDFLAGS="$saved_LDFLAGS"; unset HAVE_ZLIB
+  unset HAVE_ZLIB
+fi
+
+    echo "$as_me:$LINENO: checking for compress2" >&5
+echo $ECHO_N "checking for compress2... $ECHO_C" >&6
+if test "${ac_cv_func_compress2+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char compress2 (); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char compress2 ();
+char (*f) ();
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_compress2) || defined (__stub___compress2)
+choke me
+#else
+f = compress2;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_compress2=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_func_compress2=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_compress2" >&5
+echo "${ECHO_T}$ac_cv_func_compress2" >&6
+if test $ac_cv_func_compress2 = yes; then
+  HAVE_COMPRESS2="yes"
 fi
 
     ;;
 esac
+
+if test "x$HAVE_ZLIB" = "xyes" -a "x$HAVE_ZLIB_H" = "xyes" -a "x$HAVE_COMPRESS2" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_COMPRESSION 1
+_ACEOF
+
+fi
 
  SSL="yes"
 
@@ -28385,8 +28459,7 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 
 
 
-
-for ac_func in compress2 difftime fork gethostname getpwuid getrusage
+for ac_func in difftime fork gethostname getpwuid getrusage
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -29024,6 +29097,169 @@ echo "${ECHO_T}%${hdf5_cv_printf_ll}d and %${hdf5_cv_printf_ll}u" >&6
 cat >>confdefs.h <<_ACEOF
 #define PRINTF_LL_WIDTH "$hdf5_cv_printf_ll"
 _ACEOF
+
+
+
+for ac_header in gpfs.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ echo "$as_me:$LINENO: checking for GPFS support" >&5
+echo $ECHO_N "checking for GPFS support... $ECHO_C" >&6
+                 cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <gpfs.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+int fd = 0; gpfs_fcntl(fd, (void *)0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GPFS 1
+_ACEOF
+
+                                echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                                LIBS="$LIBS -lgpfs"
+                                GPFS="yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                                GPFS="no"
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+
+done
 
 
 echo "$as_me:$LINENO: checking for debug flags" >&5
@@ -31116,8 +31352,8 @@ IF_YES_NO() {
   else
     while test $# -gt 0; do
       if test "$1" != "yes"; then
-	PRINT "No"
-	return
+        PRINT "No"
+        return
       fi
       shift
     done
@@ -31170,7 +31406,7 @@ else
   PRINT "No"
 fi
 
-PRINT "Features:"
+PRINT "Languages:"
 
 PRINT_N "                            C++"
 IF_YES_NO "$HDF_CXX"
@@ -31178,8 +31414,16 @@ IF_YES_NO "$HDF_CXX"
 PRINT_N "                        Fortran"
 IF_YES_NO "$HDF_FORTRAN"
 
+PRINT "Features:"
+
+PRINT_N "                        dmalloc"
+IF_YES_NO "$HAVE_DMALLOC"
+
 PRINT_N "                           GASS"
 IF_YES_NO "$GASS"
+
+PRINT_N "                           GPFS"
+IF_YES_NO "$GPFS"
 
 PRINT_N "        HDF5 v1.2 Compatibility"
 IF_YES_NO "$HDF5_V1_2_COMPAT"
@@ -31211,6 +31455,3 @@ IF_ENABLED_DISABLED "$THREADSAFE"
 
 PRINT_N "               Zlib-compression"
 IF_YES_NO "$HAVE_ZLIB"
-
-PRINT_N "                        dmalloc"
-IF_YES_NO "$HAVE_DMALLOC"
