[svn-r18176] Description: 	Bring r17573:18175 from trunk to file_free_space branch.
Tested on:
        FreeBSD/32 6.3 (duty) in debug mode
        FreeBSD/64 6.3 (liberty) w/C++ & FORTRAN, in debug mode
        Linux/32 2.6 (jam) w/PGI compilers, w/default API=1.8.x,
                w/C++ & FORTRAN, w/threadsafe, in debug mode
        Linux/64-amd64 2.6 (amani) w/Intel compilers, w/default API=1.6.x,
                w/C++ & FORTRAN, in production mode
        Solaris/32 2.10 (linew) w/deprecated symbols disabled, w/C++ & FORTRAN,
                w/szip filter, in production mode
        Linux/64-ia64 2.6 (cobalt) w/Intel compilers, w/C++ & FORTRAN,
                in production mode
        Linux/64-ia64 2.4 (tg-login3) w/parallel, w/FORTRAN, in debug mode
        Linux/64-amd64 2.6 (abe) w/parallel, w/FORTRAN, in production mode

diff --git a/tools/h5dump/testh5dump.sh.in b/tools/h5dump/testh5dump.sh.in
--- a/tools/h5dump/testh5dump.sh.in
+++ b/tools/h5dump/testh5dump.sh.in
@@ -23,6 +23,10 @@ USE_FILTER_FLETCHER32="@USE_FILTER_FLETCHER32@"
 USE_FILTER_NBIT="@USE_FILTER_NBIT@"
 USE_FILTER_SCALEOFFSET="@USE_FILTER_SCALEOFFSET@"
 
+TESTNAME=h5dump
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 DUMPER=h5dump                     # The tool name
 DUMPER_BIN=`pwd`/$DUMPER          # The path of the tool binary
 TESTDIR=`pwd`/../testfiles
@@ -161,12 +165,8 @@ DIFFTEST()
 {
     PRINT_H5DIFF  $@
     (
-     cd $srcdir/../testfiles
-     if [ "`uname -s`" = "TFLOPS O/S" ]; then
-      $RUNSERIAL $H5DIFF_BIN $@ -q
-     else
-      $RUNSERIAL $H5DIFF_BIN "$@" -q
-     fi
+	cd $srcdir/../testfiles
+	$RUNSERIAL $H5DIFF_BIN "$@" -q
     )
     RET=$?
     if [ $RET != 0 ] ; then
@@ -198,12 +198,8 @@ IMPORTTEST()
 
     PRINT_H5IMPORT  $@
     (
-     cd $srcdir/../testfiles
-     if [ "`uname -s`" = "TFLOPS O/S" ]; then
-      $RUNSERIAL $H5IMPORT_BIN $@
-     else
-      $RUNSERIAL $H5IMPORT_BIN "$@" 
-     fi
+	cd $srcdir/../testfiles
+	$RUNSERIAL $H5IMPORT_BIN "$@" 
     )
     RET=$?
     if [ $RET != 0 ] ; then
@@ -517,11 +513,10 @@ TOOLTEST textlinksrc.ddl textlinksrc.h5
 TOOLTEST textlinkfar.ddl textlinkfar.h5
 
 
-
-
 if test $nerrors -eq 0 ; then
-   echo "All $DUMPER tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
-
